Custom database path support
QubesOS/qubes-rpm-oxide pull request #10
Opened 2021-11-23 02:47 UTC by DemiMarie

See individual commit messages for details.

2021-11-28 01:26 UTC, marmarek commented
PipelineRetry

2021-11-28 01:55 UTC, marmarek commented
```
DEBUG: error[E0433]: failed to resolve. Use of undeclared type or module `std`
DEBUG:   --> rpm-crypto/src/lib.rs:29:31
DEBUG:    |
DEBUG: 29 |     pub fn init(path: Option<&std::ffi::CStr>) -> InitToken {
DEBUG:    |                               ^^^ Use of undeclared type or module `std`
```

2021-11-28 01:57 UTC, marmarek commented
Please also add
```
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'
```
to `.gitlab-ci.yml`, to have the domU build tested too.

2021-11-28 03:38 UTC, marmarek requested changes

2021-11-28 03:38 UTC, marmarek commented on debian/control
> + debhelper-compat (= 13),
We do build packages for buster too, so this must be <= 12 (see CI).

2021-11-28 03:38 UTC, marmarek commented on debian/control
> +Standards-Version: 5.0.0
It seems the most recent policy version is 4.6.0.1 (https://www.debian.org/doc/debian-policy/index.html)

2021-11-28 03:38 UTC, marmarek commented on debian/control
> +Depends: ${misc:Depends}
Include `${shlibs:Depends}` too.

2021-11-28 03:38 UTC, marmarek commented on debian/rules
> +	install -D -m 0755 -- target/release/rpmcanon debian/rpmcanon
```suggestion
	install -D -m 0755 -- target/release/rpmcanon debian/tmp/usr/bin/rpmcanon
```

2021-11-28 03:38 UTC, marmarek commented on debian/rules
> +build:
```suggestion
override_dh_auto_build:
```

2021-11-28 03:38 UTC, marmarek commented on debian/rules
> +install:
```suggestion
override_dh_auto_install:
```

2021-11-28 03:38 UTC, marmarek commented on debian/rules
> +clean:
```suggestion
override_dh_auto_clean:
```

2021-11-28 03:38 UTC, marmarek commented on rpm-writer/bin/rpmcanon.rs
> +                    println!("{} bytes total", *bytes_so_far);
IMO better use consistent units - either both bytes, or both MiB. In either case, reporting progress only every 1MiB sounds fine.

2021-11-28 03:38 UTC, marmarek commented on rpm-crypto/src/lib.rs
> +    pub fn init(path: Option<&std::ffi::CStr>) -> InitToken {
This fails to build for R4.0.

2021-11-28 03:38 UTC, marmarek commented on rpm-crypto/src/lib.rs
> +                        -7
Please at least add a comment that it's `RMIL_CMDLINE`. Or define constant.

2021-11-28 13:15 UTC, marmarek commented
PipelineRetry

2021-11-30 21:00 UTC, DemiMarie commented
PipelineRetry

2021-11-30 21:25 UTC, fepitre commented
PipelineRefresh

2021-11-30 21:32 UTC, DemiMarie commented
PipelineRetry

2021-11-30 22:41 UTC, DemiMarie commented
@marmarek okay to merge?

2021-12-12 17:54 UTC, marmarek approved these changes

2021-12-12 17:54 UTC, merged